VERSION: 2
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    DEPTH: 50
  PIXEL_MEAN: [127.5, 127.5, 127.5] 
  PIXEL_STD: [1, 1, 1]
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    DEPTH: 50
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
  ANCHOR_GENERATOR:
    SIZES: [[16], [32], [64], [128], [256]]  # One size for each in feature map
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]]  # Three aspect ratios (same for all in feature maps)
  RPN:
    IN_FEATURES: ["p2", "p3", "p4", "p5", "p6"]
    PRE_NMS_TOPK_TRAIN: 2000  # Per FPN level
    PRE_NMS_TOPK_TEST: 1000  # Per FPN level
    POST_NMS_TOPK_TRAIN: 1000
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
    NAME: "ORCNNROIHeads"
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
    NUM_CLASSES: 1
  ROI_BOX_HEAD:
    NAME: "MLCFastRCNNConvFCHead"
    NUM_FC: 0
    NUM_CONV: 4
    POOLER_RESOLUTION: 7
    CLS_AGNOSTIC_BBOX_REG: True
  ROI_MASK_HEAD:
    NAME: "AmodalMaskRCNNConvUpsampleHead"
    NUM_CONV: 4
    POOLER_RESOLUTION: 14
  ROI_VISIBLE_MASK_HEAD:
    NAME: "VisibleMaskRCNNConvUpsampleHead"
    NUM_CONV: 4
    POOLER_RESOLUTION: 14
  BOXINST:
    ENABLED: False
  MASK_ON: True
  OCC_CLS_AT_BOX: False
  MULTI_LEVEL_CODING: True
  OCC_CLS_AT_MASK: True
  HIERARCHCIAL_OCCLUSION_MODELING: True
  PREDICTION_ORDER: ["V", "A", "O"]
  GUIDANCE_TYPE: "concat"

SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.00125  
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  WARMUP_ITERS: 5000
  CHECKPOINT_PERIOD: 50000
  CLIP_GRADIENTS:
    ENABLED: True
DATASETS:
  TRAIN: ("uoais_sim_train_amodal",)
  TEST: ("uoais_sim_val_amodal",)
    
TEST:
  EVAL_PERIOD: 90000 # no evaluation if 0
  EVAL_TARGET: ["amodal_visible"]

INPUT:
  MASK_FORMAT: "rle"
  IMG_SIZE: (640, 480)
  COLOR_AUGMENTATION: False
  PERLIN_DISTORTION: True
  CROP_RATIO: 0.5
  AMODAL: True 
  DEPTH: True
  DEPTH_ONLY: True
  DEPTH_RANGE: [2500, 15000]
OUTPUT_DIR: "output/R50_depth_mlc_occatmask_hom_concat"
SEED: 7
